### ISSUE TITLE
explain how to use the cli with a compiled version

### ISSUE THREAD

**Issue by MeMeMax** [PascalPons/connect4#3]
Hi, could you explain what I have to enter in the command prompt? I always get "Invalid move".

Would it be possible to expand the online api to have another parameter "width" and height in order to have a game with 9 rows?

**Comment by PascalPons** [comment]
The input in one position per input line.

The encoding of a position is just the sequence of played column number (1-based). An invalid position is either an invalid column number, invalid character, playing on a column that is already full or continuing to play after some already won. You can find more details in the second paragraph of this blog post: http://blog.gamesolver.org/solving-connect-four/02-test-protocol/

unfortunately, it is not possible to update easily the online solver to support custom board size. The solver only has precomputed opening data for the standard 7x6 board. Precomputing data for too large boards may also be untractable.

**Comment by MeMeMax** [comment]
Ok Thanks for the explanation. Is there any way to get this precomputed data into the c++ version? It takes quite a while to calculate.

**Comment by PascalPons** [comment]
by definition, you need to compute the pre-computed data at least once.
It will take quite a while (up to the eternity from a human life point of
view) on too large boards.

2017-12-06 11:32 GMT-08:00 MeMeMax <notifications@github.com>:

**Comment by MeMeMax** [comment]
Yes but 9x6 would manageable I think. How can I pre-compute the data myself and make the program use this pre computed data?

**Comment by kirarpit** [comment]
@MeMeMax, were you able to precompute the data somehow?

**Comment by MeMeMax** [comment]
No, I wasn´t.
