### ISSUE TITLE
Problem during start program

### ISSUE THREAD

**Issue by paoli7612** [PascalPons/connect4#7]
Hi. I cloned your repository, digit "make" and "./c4solver", the program start but nothing is happening. Please tell me about my error to compile or run the program. 
Thank you so much

**Comment by PascalPons** [comment]
The program most probably just waiting for an input from the standard input.

Try typing 444444 then enter for example. 

This will solve the position where both players are playing the middle column (4) 3 time each.

**Comment by paoli7612** [comment]
ok yep thank you very much
